title: gizn.se # name of the site
author: gizn # name of site's author
email: gizn@georgnaver.se # email of site's author
url: https://gizn.se # root address of the site
description: > # description of the site (multiple lines allowed)
  A collection of thoughts. Divided into shorter snippets called "TIL" (Today I Learned) and a bit longer posts called "Notes."

favicon: "./logo.png" # relative path to site's favicon

goat_counter: "gizn" # put your GoatCounter name if you want to use GoatCounter analytics

remote_theme: no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  back_home_text: "←" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

plugins:
  - jekyll-feed
  - jekyll-seo-tag